Hide the "How to translate" button (BL-9201)
BloomBooks/BloomLibrary2 pull request #190
Opened 2020-11-03 21:46 UTC by JohnThomson

2020-11-03 21:57 UTC, andrew-polk commented on src/components/BookDetail/BookDetail.tsx
> +                            {bloomDesktopAvailable && (
I'm pretty sure the intent is for it to only show up on mobile. But we don't want it to show at all for the moment since it isn't implemented.

2020-11-03 21:59 UTC, andrew-polk requested changes
To clarify:
I know we only want to hide it for now because it doesn't work.
I'm 99% sure the design is for this to only show on mobile once we implement it.

2020-11-04 14:57 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/190)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/BookDetail/BookDetail.tsx, line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/190#-MLF3pu3Zh-w4l-aItGx-r1-206:-MLIkp-_EoGzOpMdh0XK:b60qp82) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/bc20483ba8a4ec933a32437f60764af875f04e7a/src/components/BookDetail/BookDetail.tsx#L206)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty sure the intent is for it to only show up on mobile. But we don't want it to show at all for the moment since it isn't implemented.
</blockquote></details>

Makes sense. I fixed the comment accordingly.


<!-- Sent from Reviewable.io -->

2020-11-04 15:17 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/190)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-04 15:17 UTC, merged