Modernize build, test, stories
BloomBooks/BloomLibrary2 pull request #574
Opened 2024-10-28 21:56 UTC by hatton

* [x] CRA start (about 50 seconds) to vite dev (230 ms)
* [x] CRA Build (25 seconds) to vite (19 seconds)
* [x] sort out svg ulrs vs react elements
* [x] proxy api and s3 calls
* [x] get modules split
* [x] remove babel
* [x] remove need for `import {jsx}`
* [x] upgrade storybook, get running on vite
* [x] react to 17
* [x] node to 20
* [x] jest (22 seconds) --\> vitest (7 seconds)

2024-10-29 18:30 UTC, andrew-polk requested changes
> Reviewed 3 of 167 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: 144 of 167 files reviewed, 16 unresolved discussions (waiting on @hatton)

___
*[`eslint.config.mjs` line 8 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOVugS-Qq7woCmoc-K:-OAOVugS-Qq7woCmoc-L:b1bvlm) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/eslint.config.mjs#L8)):*
> ```JavaScript
>     { files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
>     // { languageOptions: { globals: globals.browser } },
>     ...tseslint.configs.recommended,
> ```

I think maybe we want these:
- plugin:react/recommended
- plugin:react-hooks/recommended
___
*[`eslint.config.mjs` line 20 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOVgQxBotte6VaEiSs:-OAOVgQxBotte6VaEiSt:br9hpkt) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/eslint.config.mjs#L20)):*
> ```JavaScript
>             ],
> 
>             "@typescript-eslint/no-explicit-any": "off",
> ```

I'm surprised to see we aren't at least warning on `any`


<!-- Sent from Reviewable.io -->

2024-11-01 16:00 UTC, andrew-polk reviewed
> Reviewed 104 of 116 files at r2, 10 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: 151 of 171 files reviewed, 3 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2024-11-01 16:01 UTC, andrew-polk reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: 151 of 171 files reviewed, 3 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2024-11-01 17:28 UTC, andrew-polk reviewed
> Reviewed 2 of 116 files at r2, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: 154 of 172 files reviewed, 3 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2024-11-11 17:33 UTC, andrew-polk reviewed
Readme looks good.
I've reviewed everything except the storybook files.

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-:-OBRHGOOCujir6JUu8-q:blp6162)* status: 155 of 173 files reviewed, 3 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2024-11-21 18:34 UTC, andrew-polk reviewed
Ok, I've reviewed everything. 

Looks like there are 4 comments remaining.

> Reviewed 16 of 167 files at r1, 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-:-OCF-JU67L7nmb9AYCH4:b-hjrdnh)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2025-01-13 18:29 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`vite.config.ts` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOIBaY1OOMJxJ-EPKA:-OGVvKEdA15E135Ij-56:bq1omyf) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/vite.config.ts#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we not want the secure prop here, too?
</blockquote></details>

Commenting again to try to make this comment display for JH...
___
*[`src/ImgWithCredits.tsx` line 37 at r7](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OBRHg-KB5tb1LPICKFm:-OGVvJbo2gD4u4zZWN1I:bq1omyf) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/a3a0cf44985b55f122292b0484fb0408db96aaf8/src/ImgWithCredits.tsx#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I can't tell if this matters, but I'll ask the question...
Did we lose something by moving away from react-image here?
</blockquote></details>

Commenting again to try to make this comment display for JH...
___
*[`src/connection/ApiConnection.ts` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOSa9Q8TipLOsUliY4:-OGVvIqG2mccXQ4haw80:bq1omyf) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/src/connection/ApiConnection.ts#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Most of the time, when running locally, we want to test against the real api.
The dev only wants to change this when running against a locally-run api.

So, if I understand correctly, when running on localhost and we want prod api, we want `/api`.
If we're running on localhost and want local api, we want `http://localhost:7071`.
Else, we want `https://api.bloomlibrary.org`.
</blockquote></details>

Commenting again to try to make this comment display for JH...
___
*[`src/connection/LibraryQueryHooks.ts` line 1374 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOSveqCagpMKRW0CND:-OGVvCoO5gTAUhSttbxc:bq1omyf) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/src/connection/LibraryQueryHooks.ts#L1374)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This looks like a change you must have been working on separately to try to search on more than one language.
We should probably move it out of this change to vite.
</blockquote></details>

Commenting again to try to make this comment display for JH...


<!-- Sent from Reviewable.io -->

2025-01-14 15:22 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`vite.config.ts` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOIBaY1OOMJxJ-EPKA:-OG_FyYX76fqv8rMQ_Rd:b-jkhbqs) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/vite.config.ts#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Commenting again to try to make this comment display for JH...
</blockquote></details>

I don't think so, S3 is already using https, so this would do anything?
___
*[`src/ImgWithCredits.tsx` line 37 at r7](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OBRHg-KB5tb1LPICKFm:-OG_HB-mCudmhiLW3MwJ:b-6ccix8) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/a3a0cf44985b55f122292b0484fb0408db96aaf8/src/ImgWithCredits.tsx#L37)):*
> **React Image** is an `<img>` tag replacement and hook for [React.js](https://facebook.github.io/react/), supporting fallback to alternate sources when loading an image fails.

We're not falling back or using alternate sources.

> If the image cannot be loaded, **`<img>` will not be rendered**, preventing a "broken" image from showing.

I could imagine us using that? Hard to prove that we aren't.

OK so it's cheaper to work around the upgrade problem then to prove we don't need it, so I've done that.
___
*[`src/connection/ApiConnection.ts` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOSa9Q8TipLOsUliY4:-OG_MC4t3petY3S9XQjg:bu96zhh) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/src/connection/ApiConnection.ts#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Commenting again to try to make this comment display for JH...
</blockquote></details>

I think you're saying that the choice of api-provider is semi-independent of whether you're running the front end-local?
___
*[`src/connection/LibraryQueryHooks.ts` line 1374 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOSveqCagpMKRW0CND:-OG_P2Bu7RQeHwRJSB-S:b-cez5gt) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/src/connection/LibraryQueryHooks.ts#L1374)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Commenting again to try to make this comment display for JH...
</blockquote></details>

what the heck was that


<!-- Sent from Reviewable.io -->

2025-01-14 17:25 UTC, andrew-polk requested changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`vite.config.ts` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOIBaY1OOMJxJ-EPKA:-OG_pr-cChUb2BGe09u_:b-mu2l8n) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/vite.config.ts#L21)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't think so, S3 is already using https, so this would do anything?
</blockquote></details>

Sorry; I don't know anything about this setting. I just noticed that the api one just above has it and this doesn't. And I didn't know if there was a reason or if it was a mistake. But if it looks good to you, I'm good.
___
*[`src/connection/ApiConnection.ts` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOSa9Q8TipLOsUliY4:-OG_qGN89A9PsClQfo-8:btqqu5l) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/src/connection/ApiConnection.ts#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think you're saying that the choice of api-provider is semi-independent of whether you're running the front end-local?
</blockquote></details>

Correct.


<!-- Sent from Reviewable.io -->

2025-01-15 17:55 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: 172 of 173 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`vite.config.ts` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOIBaY1OOMJxJ-EPKA:-OGf4ics2yX7EVDg9TA8:b-huee14) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/vite.config.ts#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I don't know anything about this setting. I just noticed that the api one just above has it and this doesn't. And I didn't know if there was a reason or if it was a mistake. But if it looks good to you, I'm good.
</blockquote></details>

would do anything --> wouldn't do anything
___
*[`src/connection/ApiConnection.ts` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOSa9Q8TipLOsUliY4:-OGf5mSS8tkWEwwT2xr2:bixt59n) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/src/connection/ApiConnection.ts#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Correct.
</blockquote></details>

Duh, sorry about that.


<!-- Sent from Reviewable.io -->

2025-01-15 18:14 UTC, andrew-polk requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/connection/ApiConnection.ts` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-OAOSa9Q8TipLOsUliY4:-OGf8V4I-R1_niWmgEed:b-lzfw5i) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/6b347e24711d9e55d72d4fb7a27f19d1ce6f7946/src/connection/ApiConnection.ts#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Duh, sorry about that.
</blockquote></details>

If I'm understanding correctly, we need all three for different scenarios.
So something like

```
    // Developer, if you want to test a local backend, temporarily uncomment this.
    //return "http://localhost:7071/v1";

    if (window.location.hostname === "localhost") {
        // When running blorg locally, we need to use a vite proxy to handle CORS issues. (See vite.config.ts)
        return "/api/v1";
    }
    
    return "https://api.bloomlibrary.org/v1";

```


<!-- Sent from Reviewable.io -->

2025-01-15 22:24 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2025-01-15 22:25 UTC, andrew-polk approved these changes
Approved. But I'm unsure if we're ready to publish.
We probably want to make sure testers have some capacity to run the site through some paces.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/574#-:-OGg3SaEAzTWRAIJPu40:b73kqug)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2025-02-12 22:35 UTC, merged